### ISSUE TITLE
both html pages broken?

### ISSUE THREAD

**Issue by BehindTheBrain** [tvachnad/Neural-Network#10]
The homepage links to the wrong simulation page, and neither seems to be displaying content as before.

**Comment by emmaajordan** [comment]
Looks like the io file need to be updated.

**Comment by BehindTheBrain** [comment]
also when run locally, which I think argues against the io file being the issue?

**Comment by emmaajordan** [comment]
You have to be running the python logging server for the links to work correctly. I think I might be able to fix it by changing the server to recognize the static path as well as the dynamic one. Right now template files are automatically recognized on the server to load, but to load in the browser it would need the address ./templates/filename.html
