### ISSUE TITLE
the number of signals is bigger than the number of axons

### ISSUE THREAD

**Issue by jburroni** [tvachnad/Neural-Network#5]
This is not feasible so we should check what are we doing wrongly.

Add this assert to spot the problem: 

```
        // if(n.astrocyte.availableEnergy<=astrocyte_settings.minEnergy)
        // n.astrocyte.replenish();
    }
    assert(this.allSignals.length < this.allAxons.length);
    if(this.logger != null){
        if(this.logger.getLastEntry() >= 19){
            this.logger.sendToServer();
```

**Comment by emmaajordan** [comment]
I think the number of signals can be more than the number of axons because a new signal can be generated before the signal reaches the neuron.

**Comment by jburroni** [comment]
Yes, that is true.
Actually, given the speed of the signal, we may have up to 30 times more signals than axons. The question is: do we want that?

**Comment by emmaajordan** [comment]
Personally I would say no because of computation cost, but I think the issue is around biological plausibility. When we decouple the display from actual simulation we could just display one signal per axon. It would make the computation a lot faster on the display side.

**Comment by BehindTheBrain** [comment]
I think this means that our post-firing inhibition (the refractory period) is too short or too weak. We don't want to artificially restrict the number of signals, but we want to tune the parameters so that the number of signals would never be more than the number of axons (2 signals on an axon at 1 time).

**Comment by emmaajordan** [comment]
I don't think we have a refractory period built in. So I guess this can be done when we switch the replenish clock over to a tick based method instead of actual time.
