### ISSUE TITLE
Neurons Decay membrane potential on a timer not on ticks

### ISSUE THREAD

**Issue by emmaajordan** [tvachnad/Neural-Network#9]
The Neuron.prototype.decay function isn't used and neurons only decay based on the decay function which use a timer. Need to make this depend on a tick based clock. Proposing this change where if a neuron doesn't receive a signal then it decays using the decay function:

``` javascript

Neuron.prototype.decay = function(){
    this.acc = 0.9 * this.acc;
    if (this.acc < 0)
        this.acc = 0;
}
Neuron.prototype.fireIfCan = function(neuralNet, currentTime)
{
    var ret = [false, null];
    if (this.willFire())
    {
        if (this.receivedSignal) {
            var astrocyte = this.astrocyteWithEnergy();
            if (astrocyte != null) { // Astrocyte mode
                var prevacc = this.acc;
                this.fire();
                ret = [true, prevacc]
                astrocyte.deplete();
                this.lastSignalRelease = currentTime;
                neuralNet.releaseSignalAt(this);
            } else {
                ret = [false, this.astrocyte.availableEnergy];
            }
            this.receivedSignal = false; // if neuron received signal but still in delay reset it
        } else {
            this.decay();
        }
    } 
    return ret;
}
```

**Comment by tvachnad** [comment]
I think this is much better than the timer.

**Comment by emmaajordan** [comment]
One question I have is setting the decay rate. This is set to 0.9, but will be that way regardless of the amount of time one tick represents. Do we want to set it to something relative to the time of one tick? For example we want ticks to be at 1ms but want it to decay to 0.9*acc at 10ms. So we have a decay rate of 0.1 per 10 ms with 1ms update ticks.  So we should calculate decay to be 1 - (decay_rate/(decay_time/update_time) = 1 - (0.1/(10/1)) = 1 - 0.01 = 0.99.

Does this seem right to everyone?
